language: java
jobs:
  include:
  - stage: Build
    script: mvn package
  - stage: SonarQube
    script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fsantiag -Dsonar.login=$SONAR_TOKEN
  - stage: Release
    script: echo "Releasing to Github..."
    deploy:
      provider: releases
      api_key:
        secure: KzOcINDHQC441MGeOPU63zNELwy7jOcPCx69zE6SPovIImsFbjOpDhCpg6al52JWd5sKOyZJvgwUrcEsvxxFSpBlp0zn9DQwTcANfyuajqiOYrf1DsTPSnPj1uknG6gPvmcTwOKRgjyn9p32F+lUmTUJqGUwSSdE3RYUgaLVoUCFK3Xu2e2ncKYR6o3SdK4pmzazhAIG2VPhqG6+8TOMBr/NS9/S/BSHCkp7H3SCzwVKUv2UGgg6art6KTx3Xy7/JOtWEpZaaSAOYYbrvBUy4rm8wxxc37CioP9sqjOvgsMSqyNQ5lpckYBw12tQEJ8Q/1z4aIeb0bsBaGfBEdLyFZywNF+rbbqzRQoglAE2Fm12Mvk3woBcBG0Z+M4uDnb2lZff8iJ3bsXlty7+WTd6QDpSoxDAWU+Qo7gipEyuON5SWkzMmkWK8ARr+js56rGH2tFDmBd91qfzETEf7HXvzv/6WY+dpAG5pgedPOkHaPjdjC4eX6Sl0Axa3ps0m5LVcGg1oYe6V8Tkfx61ehV0kT2I+VNwnD2OixgfzN74UkzS3QZvOwZ6uCGT+082kA2PtmRtARuDROrlyEighFeUKUfA7qMZsO3lqN5spvs7NvZRL8jiwn6bW0IvFBFmVzesTVPA3ObOFdf1VnEu2iTDYSSKNMkdnRuuRN4thuZErxM=
      file: sonar-clojure-plugin-1.0-SNAPSHOT.jar
      skip_cleanup: true
      on:
        repo: fsantiag/sonar-clojure
        tags: true
env:
  global:
    secure: SclOuSipO+/x21fADxux17AqdHNk+v/Fw4MDKWUBRO+OxJa0qHkMdUlwTDBYAADanraHtebUQz54gQdtm+Ovi9Yev7KCJ3Y+wWVhXrk4VJtLmyIsT8FMO10kF7IO8lpnm3EkM5kP1/KG7Q4knUUlDthyRZAvjWCJrwS+L3udrYovciypRNgWSkJTtsDMYRX2KA+e2+k/mwNpu59oFockEN7KJM8ArknOpkWqoop7xk9KQdapHkKcFA0nYAgPd3F7SWScdbk65+KjNZnaJh9tIijaQycDmvcFOsUCh/+GIT5VWsWOwoTnBHhxhyO8of9+YbsX480tI0OR4p+/JdN6xP+v+xNVkagiJoIddpVHWF4CoId1PILOayszJciUy+8iA6dv0tYkAehxSvNhJ1s7bkbTKGW/oyvJfvCJS7rwjamVASpSKux7dCy1D5+OxkkfSohZ3tUlqlRrQiE7oJgCtuKUBdyU7efMyLJT65zABumXZER9ABgdqmk7476UlQqMhVFCa7lZMzB0A5aY2ikFhg+NsWJJ8qvb9xR9TPmypVUlwaCPeE6nZkjQ7y/GSqs7gja6RJ7HX5TX8ucaTB6jmZpwJzNENTy47pJ58HAdGVgIH6Gdvu+4SFZNq2jh2DfDYgKI1+5K6Y46CzAtmmwKcOSqvZhflKy1lTOhUeEHAT8=
