language: java
jobs:
  include:
  - stage: Build
    script: mvn package
  - stage: SonarQube
    script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=fsantiag -Dsonar.login=$SONAR_TOKEN
  - stage: Release
    script: echo "Releasing to Github..."
    deploy:
      provider: releases
      api_key:
        secure: FwmoRW2wANyvOJ3UXLXc2oMiSFRbRtHHk7tSo9KHg6aXZwRGW0oyxicdCI+Dvm1re79CSqrsmMBaAx6cUYuZHQFmvaf7py7wrcs5YFDw8/B0Qt24iiFxuHO0YXa21O+jDd150EIagQwdb5ZoJvTb5F1M9Qqjh9WDqGksJZ0Q3lNNjI7xLDfSkREUybNCGhIIAeriLxzaTHIKXewnOU4dJ0tdP6Zf9ORDAzOlNh5IQtQ9a27vc59dcujYuemKaFg9zDiinjmM5UWv0anw/ZwRLKia1g/u+3nJTiI7vS0qWLjq6kot3dkOUFUQZ3kETURhgkLlGdME1o5RYJDFL+MVPs/fPzvHq+JDpcwPYRzdO3xiMAVrz6ie2UFNe9Tn4ogwWg1T1PU8nx116S7pOdIY9i8BJRB61jfmycccDPliPR2Rv0/0AknAH9fsLeUHAl0i7g6k16lawU6BtyRDTEdu+AsbSP2wwItRd4bP5AguU5RKQPTviSLt7diB3L9uGxeBAb1K6wex+lW+pPK5bRCTrq9wYpDG4ZQtNtFKyzpAjxP3kX0L2JtAF2lpStdd2ZHFzNHYiYKeVi5eJ+gctkgy6buE2MTonR2IWNI5BqAGVCJCh4qmQTU4icka83jltupXEIEDNf8l9qM1ygIUR/OvMOQBYd2C7Cc2s5tkzuIqe54=
      file: sonar-clojure-plugin-1.0-SNAPSHOT.jar
      skip_cleanup: true
      on:
        repo: fsantiag/sonar-clojure
        tags: true
env:
  global:
    secure: SclOuSipO+/x21fADxux17AqdHNk+v/Fw4MDKWUBRO+OxJa0qHkMdUlwTDBYAADanraHtebUQz54gQdtm+Ovi9Yev7KCJ3Y+wWVhXrk4VJtLmyIsT8FMO10kF7IO8lpnm3EkM5kP1/KG7Q4knUUlDthyRZAvjWCJrwS+L3udrYovciypRNgWSkJTtsDMYRX2KA+e2+k/mwNpu59oFockEN7KJM8ArknOpkWqoop7xk9KQdapHkKcFA0nYAgPd3F7SWScdbk65+KjNZnaJh9tIijaQycDmvcFOsUCh/+GIT5VWsWOwoTnBHhxhyO8of9+YbsX480tI0OR4p+/JdN6xP+v+xNVkagiJoIddpVHWF4CoId1PILOayszJciUy+8iA6dv0tYkAehxSvNhJ1s7bkbTKGW/oyvJfvCJS7rwjamVASpSKux7dCy1D5+OxkkfSohZ3tUlqlRrQiE7oJgCtuKUBdyU7efMyLJT65zABumXZER9ABgdqmk7476UlQqMhVFCa7lZMzB0A5aY2ikFhg+NsWJJ8qvb9xR9TPmypVUlwaCPeE6nZkjQ7y/GSqs7gja6RJ7HX5TX8ucaTB6jmZpwJzNENTy47pJ58HAdGVgIH6Gdvu+4SFZNq2jh2DfDYgKI1+5K6Y46CzAtmmwKcOSqvZhflKy1lTOhUeEHAT8=
